---
apiVersion: v1
kind: Namespace
metadata:
  name: netbootxyz

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbootxyz-config-pvc
  namespace: netbootxyz
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: harvester-longhorn
  resources:
    requests:
      storage: 30Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbootxyz-asset-pvc
  namespace: netbootxyz
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: harvester-longhorn
  resources:
    requests:
      storage: 300Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netbootxyz-config
  namespace: netbootxyz
data:
  RECREATE_CONFIGURATION: "1"
  http_proxy: "http://proxy-dmz.intel.com:912"
  HTTP_PROXY: "http://proxy-dmz.intel.com:912"
  https_proxy: "http://proxy-dmz.intel.com:912"
  HTTPS_PROXY: "http://proxy-dmz.intel.com:912"
  ftp_proxy: "http://proxy-dmz.intel.com:912"
  FTP_PROXY: "http://proxy-dmz.intel.com:912"
  no_proxy: "127.0.0.1,127.0.0.0/8,134.134.0.0/16,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,localhost,.local,longhorn-system,cattle-system,harvester-system,intel.com,.intel.com"
  NO_PROXY: "127.0.0.1,127.0.0.0/8,134.134.0.0/16,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,localhost,.local,longhorn-system,cattle-system,harvester-system,intel.com,.intel.com"
  MENU_VERSION: "2.0.82"
  WEB_APP_PORT: "31000"
  NGINX_PORT: "31080"
  TFTPD_OPTS: "--tftp-single-port"
  TZ: "Etc/UTC"

